<?

# Пишу скрипты, модули с 0 
# PHP <=> 7.4, MySQL, MySQL(i), AJAX
# Author Xaori69otori
# Telegram @Xaori69otori

function emoji($text) {

	$text = strtr($text, array(

	'😀' => '<img class="emoji" src="'.URL.'/assets/emoji/0_0.png">',
	'😃' => '<img class="emoji" src="'.URL.'/assets/emoji/0_1.png">',
	'😄' => '<img class="emoji" src="'.URL.'/assets/emoji/0_2.png">',
	'😁' => '<img class="emoji" src="'.URL.'/assets/emoji/0_3.png">',
	'😆' => '<img class="emoji" src="'.URL.'/assets/emoji/0_4.png">',
	'😅' => '<img class="emoji" src="'.URL.'/assets/emoji/0_5.png">',
	'😂' => '<img class="emoji" src="'.URL.'/assets/emoji/0_6.png">',
	'🤣' => '<img class="emoji" src="'.URL.'/assets/emoji/0_7.png">',
	'☺️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_8.png">',
	'😊' => '<img class="emoji" src="'.URL.'/assets/emoji/0_9.png">',
	'😇' => '<img class="emoji" src="'.URL.'/assets/emoji/0_10.png">',
	'🙂' => '<img class="emoji" src="'.URL.'/assets/emoji/0_11.png">',
	'🙃' => '<img class="emoji" src="'.URL.'/assets/emoji/0_12.png">',
	'😉' => '<img class="emoji" src="'.URL.'/assets/emoji/0_13.png">',
	'😌' => '<img class="emoji" src="'.URL.'/assets/emoji/0_14.png">',
	'😍' => '<img class="emoji" src="'.URL.'/assets/emoji/0_15.png">',
	'🥰' => '<img class="emoji" src="'.URL.'/assets/emoji/0_16.png">',
	'😘' => '<img class="emoji" src="'.URL.'/assets/emoji/0_17.png">',
	'😗' => '<img class="emoji" src="'.URL.'/assets/emoji/0_18.png">',
	'😙' => '<img class="emoji" src="'.URL.'/assets/emoji/0_19.png">',
	'😚' => '<img class="emoji" src="'.URL.'/assets/emoji/0_20.png">',
	'😋' => '<img class="emoji" src="'.URL.'/assets/emoji/0_21.png">',
	'😛' => '<img class="emoji" src="'.URL.'/assets/emoji/0_22.png">',
	'😝' => '<img class="emoji" src="'.URL.'/assets/emoji/0_23.png">',
	'😜' => '<img class="emoji" src="'.URL.'/assets/emoji/0_24.png">',
	'🤪' => '<img class="emoji" src="'.URL.'/assets/emoji/0_25.png">',
	'🤨' => '<img class="emoji" src="'.URL.'/assets/emoji/0_26.png">',
	'🧐' => '<img class="emoji" src="'.URL.'/assets/emoji/0_27.png">',
	'🤓' => '<img class="emoji" src="'.URL.'/assets/emoji/0_28.png">',
	'😎' => '<img class="emoji" src="'.URL.'/assets/emoji/0_29.png">',
	'🤩' => '<img class="emoji" src="'.URL.'/assets/emoji/0_30.png">',
	'🥳' => '<img class="emoji" src="'.URL.'/assets/emoji/0_31.png">',
	'😏' => '<img class="emoji" src="'.URL.'/assets/emoji/0_32.png">',
	'😒' => '<img class="emoji" src="'.URL.'/assets/emoji/0_33.png">',
	'😞' => '<img class="emoji" src="'.URL.'/assets/emoji/0_34.png">',
	'😔' => '<img class="emoji" src="'.URL.'/assets/emoji/0_35.png">',
	'😟' => '<img class="emoji" src="'.URL.'/assets/emoji/0_36.png">',
	'😕' => '<img class="emoji" src="'.URL.'/assets/emoji/0_37.png">',
	'🙁' => '<img class="emoji" src="'.URL.'/assets/emoji/0_38.png">',
	'☹️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_39.png">',
	'😣' => '<img class="emoji" src="'.URL.'/assets/emoji/0_40.png">',
	'😖' => '<img class="emoji" src="'.URL.'/assets/emoji/0_41.png">',
	'😫' => '<img class="emoji" src="'.URL.'/assets/emoji/0_42.png">',
	'😩' => '<img class="emoji" src="'.URL.'/assets/emoji/0_43.png">',
	'🥺' => '<img class="emoji" src="'.URL.'/assets/emoji/0_44.png">',
	'😢' => '<img class="emoji" src="'.URL.'/assets/emoji/0_45.png">',
	'😭' => '<img class="emoji" src="'.URL.'/assets/emoji/0_46.png">',
	'😤' => '<img class="emoji" src="'.URL.'/assets/emoji/0_47.png">',
	'😠' => '<img class="emoji" src="'.URL.'/assets/emoji/0_48.png">',
	'😡' => '<img class="emoji" src="'.URL.'/assets/emoji/0_49.png">',
	'🤬' => '<img class="emoji" src="'.URL.'/assets/emoji/0_50.png">',
	'🤯' => '<img class="emoji" src="'.URL.'/assets/emoji/0_51.png">',
	'😳' => '<img class="emoji" src="'.URL.'/assets/emoji/0_52.png">',
	'🥵' => '<img class="emoji" src="'.URL.'/assets/emoji/0_53.png">',
	'🥶' => '<img class="emoji" src="'.URL.'/assets/emoji/0_54.png">',
	'😱' => '<img class="emoji" src="'.URL.'/assets/emoji/0_55.png">',
	'😨' => '<img class="emoji" src="'.URL.'/assets/emoji/0_56.png">',
	'😰' => '<img class="emoji" src="'.URL.'/assets/emoji/0_57.png">',
	'😥' => '<img class="emoji" src="'.URL.'/assets/emoji/0_58.png">',
	'😓' => '<img class="emoji" src="'.URL.'/assets/emoji/0_59.png">',
	'🤗' => '<img class="emoji" src="'.URL.'/assets/emoji/0_60.png">',
	'🤔' => '<img class="emoji" src="'.URL.'/assets/emoji/0_61.png">',
	'🤭' => '<img class="emoji" src="'.URL.'/assets/emoji/0_62.png">',
	'🤫' => '<img class="emoji" src="'.URL.'/assets/emoji/0_63.png">',
	'🤥' => '<img class="emoji" src="'.URL.'/assets/emoji/0_64.png">',
	'😶' => '<img class="emoji" src="'.URL.'/assets/emoji/0_65.png">',
	'😐' => '<img class="emoji" src="'.URL.'/assets/emoji/0_66.png">',
	'😑' => '<img class="emoji" src="'.URL.'/assets/emoji/0_67.png">',
	'😬' => '<img class="emoji" src="'.URL.'/assets/emoji/0_68.png">',
	'🙄' => '<img class="emoji" src="'.URL.'/assets/emoji/0_69.png">',
	'😯' => '<img class="emoji" src="'.URL.'/assets/emoji/0_70.png">',
	'😦' => '<img class="emoji" src="'.URL.'/assets/emoji/0_71.png">',
	'😧' => '<img class="emoji" src="'.URL.'/assets/emoji/0_72.png">',
	'😮' => '<img class="emoji" src="'.URL.'/assets/emoji/0_73.png">',
	'😲' => '<img class="emoji" src="'.URL.'/assets/emoji/0_74.png">',
	'🥱' => '<img class="emoji" src="'.URL.'/assets/emoji/0_75.png">',
	'😴' => '<img class="emoji" src="'.URL.'/assets/emoji/0_76.png">',
	'🤤' => '<img class="emoji" src="'.URL.'/assets/emoji/0_77.png">',
	'😪' => '<img class="emoji" src="'.URL.'/assets/emoji/0_78.png">',
	'😵' => '<img class="emoji" src="'.URL.'/assets/emoji/0_79.png">',
	'🤐' => '<img class="emoji" src="'.URL.'/assets/emoji/0_80.png">',
	'🥴' => '<img class="emoji" src="'.URL.'/assets/emoji/0_81.png">',
	'🤢' => '<img class="emoji" src="'.URL.'/assets/emoji/0_82.png">',
	'🤮' => '<img class="emoji" src="'.URL.'/assets/emoji/0_83.png">',
	'🤧' => '<img class="emoji" src="'.URL.'/assets/emoji/0_84.png">',
	'😷' => '<img class="emoji" src="'.URL.'/assets/emoji/0_85.png">',
	'🤒' => '<img class="emoji" src="'.URL.'/assets/emoji/0_86.png">',
	'🤕' => '<img class="emoji" src="'.URL.'/assets/emoji/0_87.png">',
	'🤑' => '<img class="emoji" src="'.URL.'/assets/emoji/0_88.png">',
	'🤠' => '<img class="emoji" src="'.URL.'/assets/emoji/0_89.png">',
	'😈' => '<img class="emoji" src="'.URL.'/assets/emoji/0_90.png">',
	'👿' => '<img class="emoji" src="'.URL.'/assets/emoji/0_91.png">',
	'👹' => '<img class="emoji" src="'.URL.'/assets/emoji/0_92.png">',
	'👺' => '<img class="emoji" src="'.URL.'/assets/emoji/0_93.png">',
	'🤡' => '<img class="emoji" src="'.URL.'/assets/emoji/0_94.png">',
	'💩' => '<img class="emoji" src="'.URL.'/assets/emoji/0_95.png">',
	'👻' => '<img class="emoji" src="'.URL.'/assets/emoji/0_96.png">',
	'💀' => '<img class="emoji" src="'.URL.'/assets/emoji/0_97.png">',
	'☠️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_98.png">',
	'👽' => '<img class="emoji" src="'.URL.'/assets/emoji/0_99.png">',
	'👾' => '<img class="emoji" src="'.URL.'/assets/emoji/0_100.png">',
	'🤖' => '<img class="emoji" src="'.URL.'/assets/emoji/0_101.png">',
	'🎃' => '<img class="emoji" src="'.URL.'/assets/emoji/0_102.png">',
	'😺' => '<img class="emoji" src="'.URL.'/assets/emoji/0_103.png">',
	'😸' => '<img class="emoji" src="'.URL.'/assets/emoji/0_104.png">',
	'😹' => '<img class="emoji" src="'.URL.'/assets/emoji/0_105.png">',
	'😻' => '<img class="emoji" src="'.URL.'/assets/emoji/0_106.png">',
	'😼' => '<img class="emoji" src="'.URL.'/assets/emoji/0_107.png">',
	'😽' => '<img class="emoji" src="'.URL.'/assets/emoji/0_108.png">',
	'🙀' => '<img class="emoji" src="'.URL.'/assets/emoji/0_109.png">',
	'😿' => '<img class="emoji" src="'.URL.'/assets/emoji/0_110.png">',
	'😾' => '<img class="emoji" src="'.URL.'/assets/emoji/0_111.png">',
	'🤲' => '<img class="emoji" src="'.URL.'/assets/emoji/0_112.png">',
	'👐' => '<img class="emoji" src="'.URL.'/assets/emoji/0_118.png">',
	'🙌' => '<img class="emoji" src="'.URL.'/assets/emoji/0_124.png">',
	'👏' => '<img class="emoji" src="'.URL.'/assets/emoji/0_130.png">',
	'🤝' => '<img class="emoji" src="'.URL.'/assets/emoji/0_136.png">',
	'👍' => '<img class="emoji" src="'.URL.'/assets/emoji/0_137.png">',
	'👎' => '<img class="emoji" src="'.URL.'/assets/emoji/0_143.png">',
	'👊' => '<img class="emoji" src="'.URL.'/assets/emoji/0_149.png">',
	'✊' => '<img class="emoji" src="'.URL.'/assets/emoji/0_155.png">',
	'🤛' => '<img class="emoji" src="'.URL.'/assets/emoji/0_161.png">',
	'🤜' => '<img class="emoji" src="'.URL.'/assets/emoji/0_167.png">',
	'🤞️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_173.png">',
	'✌️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_179.png">',
	'🤟' => '<img class="emoji" src="'.URL.'/assets/emoji/0_185.png">',
	'🤘' => '<img class="emoji" src="'.URL.'/assets/emoji/0_191.png">',
	'👌' => '<img class="emoji" src="'.URL.'/assets/emoji/0_197.png">',
	'🤏' => '<img class="emoji" src="'.URL.'/assets/emoji/0_203.png">',
	'👈' => '<img class="emoji" src="'.URL.'/assets/emoji/0_209.png">',
	'👉' => '<img class="emoji" src="'.URL.'/assets/emoji/0_215.png">',
	'👆' => '<img class="emoji" src="'.URL.'/assets/emoji/0_221.png">',
	'👇' => '<img class="emoji" src="'.URL.'/assets/emoji/0_227.png">',
	'☝️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_233.png">',
	'✋' => '<img class="emoji" src="'.URL.'/assets/emoji/0_239.png">',
	'🤚' => '<img class="emoji" src="'.URL.'/assets/emoji/0_245.png">',
	'🖐' => '<img class="emoji" src="'.URL.'/assets/emoji/0_251.png">',
	'🖖' => '<img class="emoji" src="'.URL.'/assets/emoji/0_257.png">',
	'👋' => '<img class="emoji" src="'.URL.'/assets/emoji/0_263.png">',
	'🤙' => '<img class="emoji" src="'.URL.'/assets/emoji/0_269.png">',
	'💪' => '<img class="emoji" src="'.URL.'/assets/emoji/0_275.png">',
	'🦾' => '<img class="emoji" src="'.URL.'/assets/emoji/0_281.png">',
	'🖕' => '<img class="emoji" src="'.URL.'/assets/emoji/0_282.png">',
	'✍️' => '<img class="emoji" src="'.URL.'/assets/emoji/0_288.png">',
	'🙏' => '<img class="emoji" src="'.URL.'/assets/emoji/0_294.png">',
	'🦶' => '<img class="emoji" src="'.URL.'/assets/emoji/0_300.png">',
	'🦵' => '<img class="emoji" src="'.URL.'/assets/emoji/0_306.png">',
	'🦿' => '<img class="emoji" src="'.URL.'/assets/emoji/0_312.png">',
	'💄' => '<img class="emoji" src="'.URL.'/assets/emoji/0_313.png">',
	'💋' => '<img class="emoji" src="'.URL.'/assets/emoji/0_314.png">',
	'👄' => '<img class="emoji" src="'.URL.'/assets/emoji/0_315.png">',
	'🦷' => '<img class="emoji" src="'.URL.'/assets/emoji/0_316.png">',
	'👅' => '<img class="emoji" src="'.URL.'/assets/emoji/0_317.png">',
	'👂' => '<img class="emoji" src="'.URL.'/assets/emoji/0_318.png">',
	'🦻' => '<img class="emoji" src="'.URL.'/assets/emoji/0_324.png">',
	'👃' => '<img class="emoji" src="'.URL.'/assets/emoji/0_330.png">',
	'👣' => '<img class="emoji" src="'.URL.'/assets/emoji/0_336.png">',
	'👁' => '<img class="emoji" src="'.URL.'/assets/emoji/0_337.png">',
	'👀' => '<img class="emoji" src="'.URL.'/assets/emoji/0_338.png">',
	'🧠' => '<img class="emoji" src="'.URL.'/assets/emoji/0_339.png">',
	'🇺🇦' => '<img class="emoji" src="'.URL.'/assets/emoji/7_240.png">'
	));

	return $text;

}

?>